---
title: "Lab 8"
author: "Daniel Tshiani"
date: "2025-06-01"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# a

```{r}
library(ISLR)
library(dplyr)
load("../data/Auto-3.rda")

n <-  nrow(Auto)
set.seed(1234)
training_data <-  sample(n, n/2) 
train_set <- Auto[training_data, ]  
test_set  <- Auto[-training_data, ]  

model <- lm(mpg ~ weight + horsepower + acceleration, data = train_set)

model2 <- glm(mpg ~ weight + horsepower + acceleration, data = train_set)

predictions <- predict(model)
actuals <- test_set$mpg
mse <- mean((actuals - predictions)^2)
mse
```

# b
```{r}
library(boot)
regCV <- cv.glm(train_set, model)
regCV2 <- cv.glm(train_set, model2)

glimpse(regCV2)

```
# c
```{r}
cv.error <- rep(NA, 10)

for (i in 1:10) {
  model <- glm(mpg ~ poly(weight, i) + poly(horsepower, i) + poly(acceleration, i), data = train_set)
  
  cv_result <- cv.glm(train_set, model)
  
  cv.error[i] <- cv_result$delta[1]  
}
cv.error
```


# d
```{r}
model3 <- glm(mpg ~ weight + horsepower + acceleration, data = Auto)
cv_result <- cv.glm(Auto, model3, K = 10)
cv_result$delta
```



